# Site

title: D8A
description: Data, Discovery & Decision Science
logo: /images/logo.png
url: "http://d8a.org"
baseurl:

google_tagmanager: "GTM-ML6GH4"
disqus_shortname:

image: /images/d8a.png
intro: D8A is a social enterprise specializing in data, discovery & decision science.
  We promote practices and programs that benefit nature and society.

cta:
  about: Learn more about our areas of interest, mission and team members!
  projects: See what we are working on and get involved
  blog: Read our blog for updates on our projects
  home: Join our team of scientists, statisticians and storytellers!

social:
  - name: Facebook
    link: https://www.facebook.com/d8aorg
    icon: facebook
  - name: Google+
    link: https://plus.google.com/113500938723593004365
    icon: google
  - name: LinkedIn
    link: https://www.linkedin.com/company/d8aorg
    icon: linkedin
  - name: Twitter
    link: https://twitter.com/d8aorg
    icon: twitter
  
info: D8A is a social enterprise specializing in the data of everything (DoE)
email: info@d8a.org
founded: 2016
github_repo: "https://github.com/d8aorg/d8aorg.github.io"

# Build

paginate: 10
paginate_path: "/blog/:num/"

collections:
  - "people"
  - "projects"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image: /images/dots.png
      image: /images/logo.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"
      layout: post
      _comments:
        image: Shown in social shares and the blog list.

permalink: pretty

jekyll-archives:
  enabled:
    - tags

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
